export const REASON_CODES = {
  INVALID_FORMAT: "INVALID_FORMAT",
  MISSING_EVIDENCE: "MISSING_EVIDENCE",
  BLOCKED_OVERRIDE: "BLOCKED_OVERRIDE",
  FAILED_CLAIM_POLICY: "FAILED_CLAIM_POLICY",
  EMPTY_VALUE: "EMPTY_VALUE",
  NOT_ALLOWED_IN_MODE: "NOT_ALLOWED_IN_MODE",
  MISSING_APPROVED_ASSET: "MISSING_APPROVED_ASSET",
  MISSING_CRITICAL_FIELD: "MISSING_CRITICAL_FIELD",
  SECTION_POLICY_SUPPRESSED: "SECTION_POLICY_SUPPRESSED",
} as const;

export type ReasonCode = (typeof REASON_CODES)[keyof typeof REASON_CODES];
