import type { TemplateFamily } from "@/lib/template-system/types";

export const HEALTH_WELLNESS_FAMILY: TemplateFamily = {
  key: "health-wellness",
  name: "Health & Wellness",
  version: "1.0.0",
  schemaVersion: "1.0.0",
  structure: {
    defaultSectionOrder: [
      "header",
      "hero",
      "services",
      "about",
      "why-choose-us",
      "process",
      "gallery",
      "testimonials",
      "faq",
      "contact",
      "footer",
    ],
    requiredSections: [
      "header",
      "hero",
      "services",
      "about",
      "why-choose-us",
      "process",
      "faq",
      "contact",
      "footer",
    ],
    optionalSections: ["gallery", "testimonials", "service-area"],
    sectionPolicies: {
      header: { key: "header", canHide: false, requiredFields: ["businessName", "primaryPhone"], optionalFields: [], fallbackBehavior: "use-template-copy" },
      hero: { key: "hero", canHide: false, requiredFields: ["businessName", "serviceAreaLabel", "primaryCtaLabel", "primaryCtaHref"], optionalFields: ["secondaryCtaLabel", "secondaryCtaHref"], fallbackBehavior: "downgrade-to-safe-copy" },
      about: { key: "about", canHide: false, requiredFields: [], optionalFields: [], fallbackBehavior: "use-template-copy" },
      services: { key: "services", canHide: false, requiredFields: [], optionalFields: ["services"], fallbackBehavior: "use-template-copy" },
      "why-choose-us": { key: "why-choose-us", canHide: false, requiredFields: [], optionalFields: [], fallbackBehavior: "switch-variant", fallbackVariantKey: "process-heavy" },
      process: { key: "process", canHide: false, requiredFields: [], optionalFields: [], fallbackBehavior: "use-template-copy" },
      gallery: { key: "gallery", canHide: true, requiredFields: [], optionalFields: ["heroImage"], fallbackBehavior: "omit" },
      testimonials: { key: "testimonials", canHide: true, requiredFields: ["approvedTestimonials"], optionalFields: [], fallbackBehavior: "omit" },
      faq: { key: "faq", canHide: false, requiredFields: [], optionalFields: [], fallbackBehavior: "use-template-copy" },
      "service-area": { key: "service-area", canHide: true, requiredFields: ["serviceAreaLabel"], optionalFields: [], fallbackBehavior: "omit" },
      contact: { key: "contact", canHide: false, requiredFields: ["businessName", "primaryCtaLabel", "primaryCtaHref"], optionalFields: ["primaryPhone", "contactEmail"], fallbackBehavior: "use-template-copy" },
      footer: { key: "footer", canHide: false, requiredFields: ["businessName"], optionalFields: ["primaryPhone", "contactEmail"], fallbackBehavior: "use-template-copy" },
    },
  },
  resolverPolicy: {
    criticalFields: [
      "businessName",
      "primaryCtaLabel",
      "primaryCtaHref",
      "serviceAreaLabel",
    ],
    nonCriticalFields: [
      "secondaryCtaLabel",
      "secondaryCtaHref",
      "primaryPhone",
      "contactEmail",
    ],
  },
  conversionModel: {
    ctaStyle: "consultation-led",
    proofStyle: "process-heavy",
    contactPriority: ["hero", "services", "contact"],
    primaryGoal: "consult",
  },
  guardrails: {
    bannedPhrases: [
      "cutting-edge",
      "tailored solutions",
      "transform your look",
      "luxury experience unlike any other",
    ],
    bannedClaimTypes: [
      "board-certification",
      "medical-director",
      "guaranteed-results",
      "clinical-outcome",
    ],
    visualGuardrails: [
      "no glossy AI glamour",
      "no text embedded in images",
      "people imagery must be culturally diverse",
    ],
    vocabularyRules: [
      "consultation-led",
      "no urgency theater",
      "no promo-led default copy",
    ],
  },
  fieldPolicies: {},
  claimPolicies: {
    boardCertification: {
      claimType: "board-certification",
      allowed: false,
      evidenceRequired: true,
      evidenceSources: ["lead", "manual-approval"],
      sampleModeAllowed: false,
      onMissingEvidence: "suppress",
    },
    medicalDirector: {
      claimType: "medical-director",
      allowed: false,
      evidenceRequired: true,
      evidenceSources: ["lead", "manual-approval"],
      sampleModeAllowed: false,
      onMissingEvidence: "suppress",
    },
    yearsInBusiness: {
      claimType: "years-in-business",
      allowed: true,
      evidenceRequired: true,
      evidenceSources: ["lead", "manual-approval"],
      sampleModeAllowed: false,
      onMissingEvidence: "suppress",
    },
    reviewCount: {
      claimType: "review-count",
      allowed: true,
      evidenceRequired: true,
      evidenceSources: ["lead", "manual-approval"],
      sampleModeAllowed: false,
      onMissingEvidence: "suppress",
    },
    namedAwards: {
      claimType: "named-award",
      allowed: true,
      evidenceRequired: true,
      evidenceSources: ["lead", "manual-approval"],
      sampleModeAllowed: false,
      onMissingEvidence: "suppress",
    },
    namedTechnologies: {
      claimType: "named-technology",
      allowed: true,
      evidenceRequired: true,
      evidenceSources: ["lead", "manual-approval"],
      sampleModeAllowed: false,
      onMissingEvidence: "suppress",
    },
    financing: {
      claimType: "financing",
      allowed: true,
      evidenceRequired: true,
      evidenceSources: ["lead", "manual-approval"],
      sampleModeAllowed: false,
      onMissingEvidence: "suppress",
    },
    guarantees: {
      claimType: "guaranteed-results",
      allowed: false,
      evidenceRequired: true,
      evidenceSources: ["manual-approval"],
      sampleModeAllowed: false,
      onMissingEvidence: "suppress",
    },
    clinicalOutcomeClaims: {
      claimType: "clinical-outcome",
      allowed: false,
      evidenceRequired: true,
      evidenceSources: ["manual-approval"],
      sampleModeAllowed: false,
      onMissingEvidence: "suppress",
    },
    sampleTestimonials: {
      claimType: "testimonial",
      allowed: true,
      evidenceRequired: true,
      evidenceSources: ["lead", "manual-approval"],
      sampleModeAllowed: false,
      onMissingEvidence: "suppress",
    },
    promotionalOffer: {
      claimType: "promo-offer",
      allowed: true,
      evidenceRequired: true,
      evidenceSources: ["lead", "manual-approval"],
      sampleModeAllowed: false,
      onMissingEvidence: "suppress",
    },
  },
};
