// AUTO-GENERATED by scripts/generate-stock-images.ts
// Re-run with `npm run images:stock` to refresh.

import type { LeadIndustry } from "@/lib/industries";

type StockEntry = { hero: string; gallery: string[] };

export const STOCK_IMAGE_URLS: Record<LeadIndustry, StockEntry> = {
  "handyman": {
    hero: "/stock/handyman/hero.png",
    gallery: ["/stock/handyman/actionShot.png","/stock/handyman/detailShot.png","/stock/handyman/scenicShot.png"],
  },
  "pressure washing": {
    hero: "/stock/pressure-washing/hero.png",
    gallery: ["/stock/pressure-washing/actionShot.png","/stock/pressure-washing/detailShot.png","/stock/pressure-washing/scenicShot.png"],
  },
  "roofing": {
    hero: "/stock/roofing/hero.png",
    gallery: ["/stock/roofing/actionShot.png","/stock/roofing/detailShot.png","/stock/roofing/scenicShot.png"],
  },
  "HVAC": {
    hero: "/stock/hvac/hero.png",
    gallery: ["/stock/hvac/actionShot.png","/stock/hvac/detailShot.png","/stock/hvac/scenicShot.png"],
  },
  "plumbing": {
    hero: "/stock/plumbing/hero.png",
    gallery: ["/stock/plumbing/actionShot.png","/stock/plumbing/detailShot.png","/stock/plumbing/scenicShot.png"],
  },
  "dental": {
    hero: "/stock/dental/hero.png",
    gallery: ["/stock/dental/actionShot.png","/stock/dental/detailShot.png","/stock/dental/scenicShot.png"],
  },
  "med spa": {
    hero: "/stock/med-spa/hero.png",
    gallery: ["/stock/med-spa/actionShot.png","/stock/med-spa/detailShot.png","/stock/med-spa/scenicShot.png"],
  },
  "junk removal": {
    hero: "/stock/junk-removal/hero.png",
    gallery: ["/stock/junk-removal/actionShot.png","/stock/junk-removal/detailShot.png","/stock/junk-removal/scenicShot.png"],
  },
  "mobile detailing": {
    hero: "/stock/mobile-detailing/hero.png",
    gallery: ["/stock/mobile-detailing/actionShot.png","/stock/mobile-detailing/detailShot.png","/stock/mobile-detailing/scenicShot.png"],
  },
  "landscaping": {
    hero: "/stock/landscaping/hero.png",
    gallery: ["/stock/landscaping/actionShot.png","/stock/landscaping/detailShot.png","/stock/landscaping/scenicShot.png"],
  },
  "painting": {
    hero: "/stock/painting/hero.png",
    gallery: ["/stock/painting/actionShot.png","/stock/painting/detailShot.png","/stock/painting/scenicShot.png"],
  },
  "electrical": {
    hero: "/stock/electrical/hero.png",
    gallery: ["/stock/electrical/actionShot.png","/stock/electrical/detailShot.png","/stock/electrical/scenicShot.png"],
  },
  "auto repair": {
    hero: "/stock/auto-repair/hero.png",
    gallery: ["/stock/auto-repair/actionShot.png","/stock/auto-repair/detailShot.png","/stock/auto-repair/scenicShot.png"],
  },
  "pest control": {
    hero: "/stock/pest-control/hero.png",
    gallery: ["/stock/pest-control/actionShot.png","/stock/pest-control/detailShot.png","/stock/pest-control/scenicShot.png"],
  },
};

export function getStockImagesForIndustry(industry: LeadIndustry): StockEntry {
  return STOCK_IMAGE_URLS[industry];
}
