import {
  faBolt,
  faBroom,
  faCalendarCheck,
  faCar,
  faCircleCheck,
  faClock,
  faCouch,
  faDroplet,
  faEnvelope,
  faFan,
  faFireFlameCurved,
  faHandshake,
  faHouseChimney,
  faLeaf,
  faLocationDot,
  faPhone,
  faScrewdriverWrench,
  faShieldHalved,
  faShower,
  faSnowflake,
  faSoap,
  faSpa,
  faStar,
  faTooth,
  faTrashCan,
  faTruckRampBox,
  faWarehouse,
  faWrench,
  type IconDefinition,
} from "@fortawesome/free-solid-svg-icons";
import type { PreviewIcon } from "@/lib/preview/types";

export const ICON_MAP: Record<PreviewIcon, IconDefinition> = {
  bolt: faBolt,
  broom: faBroom,
  "calendar-check": faCalendarCheck,
  car: faCar,
  "circle-check": faCircleCheck,
  clock: faClock,
  couch: faCouch,
  droplet: faDroplet,
  envelope: faEnvelope,
  fan: faFan,
  "fire-flame-curved": faFireFlameCurved,
  handshake: faHandshake,
  "house-chimney": faHouseChimney,
  leaf: faLeaf,
  "location-dot": faLocationDot,
  phone: faPhone,
  "screwdriver-wrench": faScrewdriverWrench,
  "shield-halved": faShieldHalved,
  shower: faShower,
  snowflake: faSnowflake,
  soap: faSoap,
  spa: faSpa,
  star: faStar,
  tooth: faTooth,
  "trash-can": faTrashCan,
  "truck-ramp-box": faTruckRampBox,
  warehouse: faWarehouse,
  wrench: faWrench,
};
