import {
  faBolt,
  faBroom,
  faBug,
  faCalendarCheck,
  faCar,
  faCircleCheck,
  faClock,
  faCouch,
  faDroplet,
  faEnvelope,
  faFan,
  faFireFlameCurved,
  faGauge,
  faHandshake,
  faHouseChimney,
  faLeaf,
  faLightbulb,
  faLocationDot,
  faOilCan,
  faPaintRoller,
  faPaintbrush,
  faPhone,
  faPlug,
  faScissors,
  faScrewdriverWrench,
  faShieldHalved,
  faShower,
  faSnowflake,
  faSoap,
  faSpa,
  faSprayCanSparkles,
  faStar,
  faTooth,
  faTrashCan,
  faTree,
  faTruckRampBox,
  faWarehouse,
  faWrench,
  type IconDefinition,
} from "@fortawesome/free-solid-svg-icons";
import type { PreviewIcon } from "@/lib/preview/types";

export const ICON_MAP: Record<PreviewIcon, IconDefinition> = {
  bolt: faBolt,
  broom: faBroom,
  bug: faBug,
  "calendar-check": faCalendarCheck,
  car: faCar,
  "circle-check": faCircleCheck,
  clock: faClock,
  couch: faCouch,
  droplet: faDroplet,
  envelope: faEnvelope,
  fan: faFan,
  "fire-flame-curved": faFireFlameCurved,
  gauge: faGauge,
  handshake: faHandshake,
  "house-chimney": faHouseChimney,
  leaf: faLeaf,
  lightbulb: faLightbulb,
  "location-dot": faLocationDot,
  "oil-can": faOilCan,
  "paint-roller": faPaintRoller,
  paintbrush: faPaintbrush,
  phone: faPhone,
  plug: faPlug,
  scissors: faScissors,
  "screwdriver-wrench": faScrewdriverWrench,
  "shield-halved": faShieldHalved,
  shower: faShower,
  snowflake: faSnowflake,
  soap: faSoap,
  spa: faSpa,
  "spray-can-sparkles": faSprayCanSparkles,
  star: faStar,
  tooth: faTooth,
  "trash-can": faTrashCan,
  tree: faTree,
  "truck-ramp-box": faTruckRampBox,
  warehouse: faWarehouse,
  wrench: faWrench,
};
