import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { TARGET_INDUSTRIES, type LeadIndustry } from "@/lib/industries";
import { generateGeminiImage } from "@/lib/images/gemini";
import { STOCK_SLOTS, buildStockPrompt, type StockSlot } from "@/lib/images/stock-prompts";

const CONCURRENCY = 3;

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const PROJECT_ROOT = path.resolve(__dirname, "..");
const STOCK_DIR = path.join(PROJECT_ROOT, "public", "stock");
const GENERATED_PATH = path.resolve(
  PROJECT_ROOT,
  "src",
  "lib",
  "images",
  "industry-stock.generated.ts"
);

function industrySlug(industry: LeadIndustry): string {
  return industry.toLowerCase().replace(/\s+/g, "-");
}

type SlotResult = {
  industry: LeadIndustry;
  slot: StockSlot;
  publicUrl: string;
};

async function ensureDir(dir: string) {
  await fs.mkdir(dir, { recursive: true });
}

async function generateOne(
  industry: LeadIndustry,
  slot: StockSlot
): Promise<SlotResult> {
  const prompt = buildStockPrompt(industry, slot);
  process.stdout.write(`  • ${industry} / ${slot} … `);
  const image = await generateGeminiImage({ prompt, timeoutMs: 120_000 });
  const ext = image.mimeType === "image/jpeg" ? "jpg" : "png";
  const slug = industrySlug(industry);
  const dir = path.join(STOCK_DIR, slug);
  await ensureDir(dir);
  const filePath = path.join(dir, `${slot}.${ext}`);
  await fs.writeFile(filePath, Buffer.from(image.base64, "base64"));
  const publicUrl = `/stock/${slug}/${slot}.${ext}`;
  process.stdout.write(`✓ ${publicUrl}\n`);
  return { industry, slot, publicUrl };
}

async function runWithConcurrency<T>(
  tasks: Array<() => Promise<T>>,
  limit: number
): Promise<T[]> {
  const results: T[] = [];
  let cursor = 0;
  async function worker() {
    while (cursor < tasks.length) {
      const idx = cursor++;
      try {
        results[idx] = await tasks[idx]();
      } catch (err) {
        console.error(`task ${idx} failed:`, err instanceof Error ? err.message : err);
        // Continue on failure so a single bad image doesn't kill the whole run.
      }
    }
  }
  const workers = Array.from({ length: Math.min(limit, tasks.length) }, () => worker());
  await Promise.all(workers);
  return results.filter(Boolean);
}

function buildGeneratedFile(results: SlotResult[]): string {
  const byIndustry = new Map<LeadIndustry, Partial<Record<StockSlot, string>>>();
  for (const r of results) {
    const existing = byIndustry.get(r.industry) ?? {};
    existing[r.slot] = r.publicUrl;
    byIndustry.set(r.industry, existing);
  }

  const lines: string[] = [];
  lines.push("// AUTO-GENERATED by scripts/generate-stock-images.ts");
  lines.push("// Re-run with `npm run images:stock` to refresh.");
  lines.push("");
  lines.push('import type { LeadIndustry } from "@/lib/industries";');
  lines.push("");
  lines.push("type StockEntry = { hero: string; gallery: string[] };");
  lines.push("");
  lines.push("export const STOCK_IMAGE_URLS: Record<LeadIndustry, StockEntry> = {");
  for (const industry of TARGET_INDUSTRIES.map((opt) => opt.value as LeadIndustry)) {
    const entry = byIndustry.get(industry);
    if (!entry || !entry.hero) {
      lines.push(`  ${JSON.stringify(industry)}: { hero: "", gallery: [] },`);
      continue;
    }
    const gallery = (["actionShot", "detailShot", "scenicShot"] as const)
      .map((slot) => entry[slot])
      .filter((v): v is string => Boolean(v));
    lines.push(`  ${JSON.stringify(industry)}: {`);
    lines.push(`    hero: ${JSON.stringify(entry.hero)},`);
    lines.push(`    gallery: ${JSON.stringify(gallery)},`);
    lines.push(`  },`);
  }
  lines.push("};");
  lines.push("");
  lines.push(
    "export function getStockImagesForIndustry(industry: LeadIndustry): StockEntry {"
  );
  lines.push("  return STOCK_IMAGE_URLS[industry];");
  lines.push("}");
  lines.push("");
  return lines.join("\n");
}

async function main() {
  const argIndustries = process.argv.slice(2);
  const industries = (
    argIndustries.length > 0
      ? (argIndustries as LeadIndustry[])
      : TARGET_INDUSTRIES.map((opt) => opt.value as LeadIndustry)
  );

  console.log(
    `Generating stock images for ${industries.length} industries × ${STOCK_SLOTS.length} slots = ${industries.length * STOCK_SLOTS.length} images.`
  );
  console.log(`Writing to ${STOCK_DIR}/<industry>/<slot>.png`);
  console.log("");

  await ensureDir(STOCK_DIR);

  const tasks: Array<() => Promise<SlotResult>> = [];
  for (const industry of industries) {
    for (const slot of STOCK_SLOTS) {
      tasks.push(() => generateOne(industry, slot));
    }
  }

  const results = await runWithConcurrency(tasks, CONCURRENCY);

  // Merge with existing entries already present in the generated file so a
  // partial regen of a single industry doesn't wipe the others.
  let existing: Record<string, { hero: string; gallery: string[] }> = {};
  try {
    const raw = await fs.readFile(GENERATED_PATH, "utf-8");
    const match = raw.match(/STOCK_IMAGE_URLS[^=]*=\s*({[\s\S]*?});/);
    if (match) {
      existing = (0, eval)(`(${match[1]})`) as typeof existing;
    }
  } catch {
    // file doesn't exist yet — that's fine
  }

  const slotByIndustry = new Map<LeadIndustry, Partial<Record<StockSlot, string>>>();
  for (const [ind, entry] of Object.entries(existing) as Array<
    [LeadIndustry, { hero: string; gallery: string[] }]
  >) {
    if (entry.hero) {
      slotByIndustry.set(ind, {
        hero: entry.hero,
        actionShot: entry.gallery[0],
        detailShot: entry.gallery[1],
        scenicShot: entry.gallery[2],
      });
    }
  }
  for (const r of results) {
    const cur = slotByIndustry.get(r.industry) ?? {};
    cur[r.slot] = r.publicUrl;
    slotByIndustry.set(r.industry, cur);
  }
  const merged: SlotResult[] = [];
  for (const [industry, entry] of slotByIndustry.entries()) {
    for (const slot of STOCK_SLOTS) {
      const url = entry[slot];
      if (url) merged.push({ industry, slot, publicUrl: url });
    }
  }

  const fileBody = buildGeneratedFile(merged);
  await fs.writeFile(GENERATED_PATH, fileBody, "utf-8");
  console.log("");
  console.log(`Wrote ${GENERATED_PATH}`);
  console.log(`Done. ${results.length}/${tasks.length} images generated.`);
}

main().catch((err) => {
  console.error("\nstock-image generation failed:", err);
  process.exitCode = 1;
});
